# WARNING:
# Do not use this file as a template for you repository TravisCI configuration
# Instead use the template at https://github.com/OCA/oca-addons-repo-template
language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow

matrix:
  include:
    - python: 3.7
      env:
        VERSION="12.0" ODOO_REPO="OCA/OCB" TESTS="1" LINT_CHECK="1"
        INCLUDE="test_module,second_module"
        SERVER_EXPECTED_ERRORS="1"  # Supporting broken_uninstallable module after https://github.com/odoo/odoo/commit/c5d6a39

install:
  - cp -r ../maintainer-quality-tools/ $HOME
  - cp -r tests/test_repo/* ./
  - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
  # Fix AttributeError: 'str' object has no attribute 'name'
  #   https://stackoverflow.com/a/59549323/3753497
  - pip install -U --force-reinstall pluggy
   # Force install lint requirements in all cases of MQT for self_test script.
  - pip install coverage
  - LINT_CHECK="1" travis_install_nightly 8.0 # only used if VERSION not set in env
  - git --git-dir=${TRAVIS_BUILD_DIR}/.git add --all  # All modules moved are modules changed to test PR changes

script:
  - TRAVIS_PULL_REQUEST="1" coverage run ./travis/travis_run_tests 8.0  # only used if VERSION not set in env
  - coverage run --append ./travis/self_tests

after_success:
   # Seudo-fix for codecov that is not processing "data_file" parameter
   # More info about: https://github.com/codecov/codecov-python/issues/120
  - cp ./.coverage_mqt ./.coverage
  - TESTS="1" LINT_CHECK="0" travis_after_tests_success
